version: "3.9"

services:
  # bot:
  #   image: ghcr.io/laynexx/math-pdf-saver-bot:latest
  #   container_name: mpsb_bot
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   networks:
  #     - mpsb-network

  postgres:
    image: postgres:16
    container_name: mpsb_postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - /etc/storage/mpsb/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - mpsb-network

  redis:
    image: redis:latest
    ports:
      - 6380:6379
    container_name: mpsb_redis
    restart: unless-stopped
    volumes:
      - /etc/storage/mpsb/redis:/data
    networks:
      - mpsb-network

networks:
  mpsb-network:
    driver: bridge
